"""add_voting_duration_value_object

Revision ID: 674237b0f9fb
Revises: 9620b5d8e2e0
Create Date: 2026-05-10 13:14:26.596721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '674237b0f9fb'
down_revision: Union[str, None] = '9620b5d8e2e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
